# Generated by Django 4.1.5 on 2023-01-09 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("chapter_school", models.CharField(max_length=50)),
                ("city_state", models.CharField(max_length=50)),
                ("original_founding_date", models.DateField()),
                ("recharter_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=25)),
                ("nickname", models.CharField(max_length=20)),
                ("nickname_meaning", models.TextField(max_length=250)),
                (
                    "crossing_class",
                    models.CharField(
                        choices=[
                            ("01", "Alpha"),
                            ("02", "Beta"),
                            ("03", "Gamma"),
                            ("04", "Delta"),
                            ("05", "Epsilon"),
                            ("06", "Zeta"),
                            ("07", "Eta"),
                            ("08", "Theta"),
                            ("09", "Iota"),
                            (10, "Lambda"),
                            (11, "Mu"),
                            (12, "Nu"),
                            (13, "Xi"),
                            (14, "Omicron"),
                            (15, "Pi"),
                            (16, "Rho"),
                            (17, "Sigma"),
                            (18, "Tau"),
                            (19, "Upsilon"),
                            (20, "Phi"),
                            (21, "Chi"),
                            (22, "Psi"),
                            (23, "Omega"),
                        ],
                        default=None,
                        max_length=2,
                    ),
                ),
                ("crossing_semester", models.CharField(max_length=6)),
                ("crossing_year", models.IntegerField()),
                ("tree", models.CharField(max_length=20)),
                ("line_number", models.IntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Active"),
                            ("AL", "Alumnae"),
                            ("DE", "Deceased"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                (
                    "big_sister",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.sister",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_chapter",
                        to="main_app.chapter",
                    ),
                ),
                (
                    "crossing_chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crossing_chapter",
                        to="main_app.chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pnm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=25)),
                ("process_semester", models.CharField(max_length=6)),
                ("process_year", models.PositiveSmallIntegerField()),
                ("potential_line_number", models.PositiveSmallIntegerField()),
                (
                    "big_sister",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_app.sister",
                    ),
                ),
                (
                    "process_chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="process_chapter",
                        to="main_app.chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nickname_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "req_date",
                    models.DateTimeField(
                        auto_created=True,
                        default=datetime.datetime(
                            2023, 1, 9, 15, 29, 10, 150107, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="date requested",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="nickname request"),
                ),
                ("nickname_meaning", models.TextField(max_length=250)),
                (
                    "nickname_approval_status",
                    models.CharField(
                        choices=[
                            ("RE", "Requested"),
                            ("AP", "Approved"),
                            ("QU", "Queued"),
                            ("DE", "Denied"),
                        ],
                        default="RE",
                        max_length=2,
                        verbose_name="Nickname Approval Status",
                    ),
                ),
                (
                    "pnm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.pnm",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.sister",
                    ),
                ),
            ],
        ),
    ]
