# Generated by Django 4.1.5 on 2023-01-09 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_industry_alter_nickname_request_req_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sister",
            name="crossing_semester",
        ),
        migrations.RemoveField(
            model_name="sister",
            name="crossing_year",
        ),
        migrations.AddField(
            model_name="sister",
            name="coach",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sister",
            name="crossing_date",
            field=models.DateTimeField(default=None, verbose_name="crossing date"),
        ),
        migrations.AddField(
            model_name="sister",
            name="current_city",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="sister",
            name="current_company",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sister",
            name="current_country",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="sister",
            name="current_position",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="sister",
            name="current_state",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="sister",
            name="email_address",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="sister",
            name="expertise_interests",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main_app.industry",
            ),
        ),
        migrations.AddField(
            model_name="sister",
            name="initiation_date",
            field=models.DateTimeField(
                default=None, verbose_name="PNM initiation date"
            ),
        ),
        migrations.AddField(
            model_name="sister",
            name="linkedin_url",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sister",
            name="summary",
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="job_opps_and_referrals",
            name="pub_date",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2023, 1, 9, 19, 38, 19, 102250, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
        ),
        migrations.AlterField(
            model_name="nickname_request",
            name="req_date",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2023, 1, 9, 19, 38, 19, 101981, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date requested",
            ),
        ),
    ]
