# Generated by Django 4.1.5 on 2023-02-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_alter_sister_big_sister_nb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sister",
            name="big_sister_nb",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.sister",
            ),
            preserve_default=False,
        ),
    ]
