# Generated by Django 4.1.5 on 2023-01-10 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_remove_sister_crossing_semester_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="name",
        ),
        migrations.AddField(
            model_name="chapter",
            name="associate_chapter",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="greek_letter_assigned",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="job_opps_and_referrals",
            name="pub_date",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2023, 1, 10, 19, 38, 39, 286035, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
        ),
        migrations.AlterField(
            model_name="nickname_request",
            name="req_date",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2023, 1, 10, 19, 38, 39, 285733, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date requested",
            ),
        ),
    ]
