# Generated by Django 4.1.5 on 2023-01-12 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_remove_chapter_name_chapter_associate_chapter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="chapter_status",
            field=models.CharField(
                choices=[("AC", "Active"), ("IN", "Inactive")],
                default="AC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="greek_letter_assigned",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="job_opps_and_referrals",
            name="industry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_app.industry",
            ),
        ),
        migrations.AlterField(
            model_name="job_opps_and_referrals",
            name="pub_date",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2023, 1, 12, 19, 55, 14, 925254, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
        ),
        migrations.AlterField(
            model_name="nickname_request",
            name="req_date",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2023, 1, 12, 19, 55, 14, 924909, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date requested",
            ),
        ),
        migrations.AlterField(
            model_name="nickname_request",
            name="requestor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_app.sister",
            ),
        ),
        migrations.AlterField(
            model_name="sister",
            name="big_sister",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main_app.sister"
            ),
        ),
        migrations.AlterField(
            model_name="sister",
            name="current_company",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="sister",
            name="current_position",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="sister",
            name="email_address",
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="sister",
            name="expertise_interests",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.industry",
            ),
        ),
        migrations.AlterField(
            model_name="sister",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="sister",
            name="summary",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="sister",
            name="tree",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
