# Generated by Django 4.1.5 on 2023-01-12 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_chapter_chapter_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_opps_and_referrals",
            name="pub_date",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2023, 1, 12, 19, 55, 42, 145902, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
        ),
        migrations.AlterField(
            model_name="nickname_request",
            name="req_date",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2023, 1, 12, 19, 55, 42, 145605, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date requested",
            ),
        ),
    ]
