# Generated by Django 4.1.5 on 2023-02-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_chapter_stats_remove_sister_user_myuser_sister_nb_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="sister_nb",
        ),
        migrations.AddField(
            model_name="myuser",
            name="member_nb",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main_app.sister",
            ),
        ),
    ]
