# Generated by Django 4.1.5 on 2023-03-28 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_chapter_stats_remove_sister_user_myuser_member_nb_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_created=True,
                        default=django.utils.timezone.now,
                        verbose_name="date requested",
                    ),
                ),
                ("national_announcement_fg", models.BooleanField(default=True)),
                ("title_txt", models.CharField(max_length=60)),
                ("description_txt", models.CharField(max_length=280)),
                ("link_txt", models.CharField(blank=True, max_length=500, null=True)),
                ("start_posting_date", models.DateField(blank=True, null=True)),
                ("end_posting_date", models.DateField(blank=True, null=True)),
                ("approved_fg", models.BooleanField(default=False)),
                (
                    "chapter_announcement_nb",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_app.chapter",
                    ),
                ),
            ],
        ),
    ]
