# Generated by Django 4.1.5 on 2023-04-03 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0008_announcements"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sister",
            new_name="Member",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="big_sister_nb",
            new_name="big_nb",
        ),
        migrations.RenameField(
            model_name="member_experiences",
            old_name="sister_nb",
            new_name="member_nb",
        ),
        migrations.RenameField(
            model_name="pnm",
            old_name="big_sister_nb",
            new_name="big_nb",
        ),
    ]
