# Generated by Django 4.1.5 on 2023-03-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0008_remove_myuser_sister_nb_myuser_member_nb"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("national_event", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=250)),
                ("date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(max_length=50)),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FU", "Fundraising"),
                            ("SE", "Service"),
                            ("PR", "Professional"),
                            ("SI", "Sisterhood"),
                            ("ED", "Educational"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "host_chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.chapter",
                    ),
                ),
            ],
        ),
    ]
