# Generated by Django 4.1.5 on 2023-04-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0009_rename_sister_member_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["-associate_chapter_fg", "original_founding_date"]},
        ),
        migrations.RenameField(
            model_name="chapter_stats",
            old_name="deceased_nb",
            new_name="memorial_nb",
        ),
        migrations.AddField(
            model_name="chapter_stats",
            name="average_class_crossed_fl",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chapter_stats",
            name="largest_class_crossed_nb",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chapter_stats",
            name="smallest_class_crossed_nb",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="member",
            name="crossing_class_txt",
            field=models.CharField(
                choices=[
                    ("00", "Charter"),
                    ("01", "Alpha"),
                    ("02", "Beta"),
                    ("03", "Gamma"),
                    ("04", "Delta"),
                    ("05", "Epsilon"),
                    ("06", "Zeta"),
                    ("07", "Eta"),
                    ("08", "Theta"),
                    ("09", "Iota"),
                    (10, "Lambda"),
                    (11, "Mu"),
                    (12, "Nu"),
                    (13, "Xi"),
                    (14, "Omicron"),
                    (15, "Pi"),
                    (16, "Rho"),
                    (17, "Sigma"),
                    (18, "Tau"),
                    (19, "Upsilon"),
                    (20, "Phi"),
                    (21, "Chi"),
                    (22, "Psi"),
                    (23, "Omega"),
                ],
                default=None,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="current_city_txt",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="current_state_txt",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="status_txt",
            field=models.CharField(
                choices=[
                    ("AC", "Active"),
                    ("IM", "Inactive - Matriculated"),
                    ("IN", "Inactive - Non-Matriculated"),
                    ("TA", "Transfer - Active"),
                    ("TI", "Transfer - Inactive"),
                    ("TU", "Transfer - Unknown Status"),
                    ("AL", "Alumnae"),
                    ("ME", "Memorial"),
                    ("PI", "Permanent Inactivity"),
                ],
                default="AC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="position_titles",
            name="job_family_txt",
            field=models.CharField(
                choices=[
                    ("FI", "Finance"),
                    ("CS", "Community Service"),
                    ("FU", "Fundraising"),
                    ("SH", "Sisterhood"),
                    ("IN", "Intake"),
                    ("OP", "Operations"),
                    ("ED", "Education"),
                    ("RE", "Recruiting"),
                    ("PR", "Public Relations"),
                ],
                default="FI",
                max_length=2,
            ),
        ),
    ]
