# Generated by Django 4.1.5 on 2023-04-05 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0010_alter_chapter_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dialect_txt", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ethnicities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ethnicity_txt", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="member",
            name="big_nb",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main_app.member"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="crossing_class_txt",
            field=models.CharField(
                choices=[
                    ("00", "Charter"),
                    ("01", "Alpha"),
                    ("02", "Beta"),
                    ("03", "Gamma"),
                    ("04", "Delta"),
                    ("05", "Epsilon"),
                    ("06", "Zeta"),
                    ("07", "Eta"),
                    ("08", "Theta"),
                    ("09", "Iota"),
                    (10, "Lambda"),
                    (11, "Mu"),
                    (12, "Nu"),
                    (13, "Xi"),
                    (14, "Omicron"),
                    (15, "Pi"),
                    (16, "Rho"),
                    (17, "Sigma"),
                    (18, "Tau"),
                    (19, "Upsilon"),
                    (20, "Phi"),
                    (21, "Chi"),
                    (22, "Psi"),
                    (23, "Omega"),
                    (24, "Alpha Alpha"),
                    (25, "Alpha Beta"),
                    (26, "Alpha Gamma"),
                    (27, "Alpha Delta"),
                    (28, "Alpha Epsilon"),
                    (29, "Alpha Zeta"),
                    (30, "Alpha Eta"),
                    (31, "Alpha Theta"),
                    (32, "Alpha Iota"),
                    (33, "Alpha Lambda"),
                    (34, "Alpha Mu"),
                    (35, "Alpha Nu"),
                    (36, "Alpha Xi"),
                    (37, "Alpha Omicron"),
                    (38, "Alpha Pi"),
                    (39, "Alpha Rho"),
                    (40, "Alpha Sigma"),
                    (41, "Alpha Tau"),
                    (42, "Alpha Upsilon"),
                    (43, "Alpha Phi"),
                    (44, "Alpha Chi"),
                    (45, "Alpha Psi"),
                    (46, "Alpha Omega"),
                    (47, "Beta Alpha"),
                    (48, "Beta Beta"),
                    (49, "Beta Gamma"),
                    (50, "Beta Delta"),
                    (51, "Beta Epsilon"),
                    (52, "Beta Zeta"),
                    (53, "Beta Eta"),
                    (54, "Beta Theta"),
                    (55, "Beta Iota"),
                    (56, "Beta Lambda"),
                    (57, "Beta Mu"),
                    (58, "Beta Nu"),
                    (59, "Beta Xi"),
                    (60, "Beta Omicron"),
                    (61, "Beta Pi"),
                    (62, "Beta Rho"),
                    (63, "Beta Sigma"),
                    (64, "Beta Tau"),
                    (65, "Beta Upsilon"),
                    (66, "Beta Phi"),
                    (67, "Beta Chi"),
                    (68, "Beta Psi"),
                    (69, "Beta Omega"),
                ],
                default=None,
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="dialects_txt",
            field=models.ManyToManyField(to="main_app.dialects"),
        ),
        migrations.AddField(
            model_name="member",
            name="ethnicity_txt",
            field=models.ManyToManyField(to="main_app.ethnicities"),
        ),
    ]
