# Generated by Django 4.1.5 on 2023-07-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0012_alter_dialects_options_alter_ethnicities_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={
                "ordering": [
                    "associate_chapter_fg",
                    "greek_letter_assigned_txt",
                    "original_founding_date",
                ]
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="inactive_chapter_fg",
            field=models.BooleanField(default=False),
        ),
    ]
