# Generated by Django 4.1.5 on 2023-07-25 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0013_alter_chapter_options_chapter_inactive_chapter_fg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="inactive_chapter_fg",
        ),
    ]
